name: docker-compose-guest-mysql
services:
  mysqlservice:
    container_name: docker_compose_mysql_container
    build:
      context: ./
      dockerfile: DockerfileMySQL
    volumes:
     - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306
  guestservice2:
    depends_on:
      - mysqlservice
    container_name: docker_compose_guest_container2
    build:
      context: ./
      dockerfile: DockerfileGuest
    command: ["-jar", "-Dspring.profiles.active=prod-mysql","app.jar"]  
    ports:
      - 80:80
    restart: on-failure 
volumes:
  mysql_volume:
    external: true
